server {
    listen 80;

    location /api/catalog {
        proxy_pass http://catalog_api:8000/;
    }

    location /api/orders {
        proxy_pass http://order_api:8000/;
    }

    location /docs {
        proxy_pass http://catalog_api:8000/docs;
    }

    location /openapi.json {
        proxy_pass http://catalog_api:8000/openapi.json;
    }
}